spring:
  jpa:
    showSql: true

    hibernate:
      ddlAuto: update

  datasource:
    url: jdbc:mysql://localhost:3306/{DatabaseName}
    username: {name}
    password: {password}
    driverClassName: com.mysql.cj.jdbc.Driver